### PR TITLE
Added structured data to the waterbudget skeleton html.

### PR DESCRIPTION
**Pull request by mbucknell**
Added structured json-ld data for the three data services: daymet, eta, and wfs GetFeature. I also modified the template to more closely reflect the content of the actual page.

### CODE REVIEW

**Comment by mbucknell** [comment]
@dblodgett-usgs , take a look. I didn't really see any other appropriate tags. There is keywords tag for the Dataset object. See http://schema.org/Dataset for the full list. This is the model I'll follow for the streamflow pages. Will also add the huc8 pages but wanted you to review this.

**Comment by jiwalker-usgs** [comment]
This is very cool :+1:

**Comment by dblodgett-usgs** [comment]
Looks great to me!

**Comment by mbucknell** [comment]
Added a data_config.json that is read by the generate* scripts and then used to call the services and used in the templates. The majority of the changes are in the templates to add the structured data and to make the content more closely match the actual pages.

**Pull request merged**
